Import('env')

env.InstallHTML(['img/logo.png', 'img/logo2.gif', 'img/debye.png',
                 'img/chi.gif', 'img/zoom_out_icon.png'], 'img')

env.InstallHTML(['css/foxs.css'], 'css')

SConscript('examples/SConscript')
SConscript('example2/SConscript')
